# Generated by Django 4.2.3 on 2023-07-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Manager'), (2, 'Staff'), (3, 'Client')], default=1, max_length=10),
        ),
    ]
