# Generated by Django 4.2.3 on 2023-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='actual_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='estimated_budget',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='feature_image',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='plan',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='sub_county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
