# Generated by Django 4.2.3 on 2023-07-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_courses_actual_cost_courses_city_courses_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_management_app.staffs'),
        ),
    ]
