# Generated by Django 4.2.3 on 2023-07-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_courses_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstaffs',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedbackstaffs',
            name='image_update',
            field=models.FileField(blank=True, null=True, upload_to='feedback/'),
        ),
        migrations.AddField(
            model_name='feedbackstaffs',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_management_app.courses'),
        ),
        migrations.AddField(
            model_name='feedbackstaffs',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedbackstaffs',
            name='video_update',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
