# Generated by Django 4.2.3 on 2023-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_feedbackstaffs_category_feedbackstaffs_image_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='jobgroup',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
